# Generated by Django 4.0.4 on 2022-05-14 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('Name', models.CharField(max_length=255)),
                ('dateBirth', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('numVotes', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('startData', models.DateField()),
                ('endDate', models.DateField()),
                ('Description', models.TextField(blank=True)),
                ('numCandidates', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11)),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appES.candidate')),
                ('Election', models.ManyToManyField(default=0, to='appES.election')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='Election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appES.election'),
        ),
    ]
