# Generated by Django 4.0.4 on 2022-05-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='numVotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
