# Generated by Django 4.0.4 on 2022-05-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appES', '0002_alter_candidate_numvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='Election',
            field=models.ManyToManyField(default=[0], to='appES.election'),
        ),
    ]
