# Generated by Django 4.0.4 on 2022-05-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appES', '0004_alter_candidate_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='Winner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
